### ISSUE TITLE
Problem with spdl.py

### ISSUE THREAD

**Issue by abhijitb81** [mityax/spdl.py-southpark-downloader#1]
```
Collecting episodes to download...
Traceback (most recent call last):
  File "D:\spdl-southpark\spdl.py", line 489, in <module>
    for season in s.get_all_seasons():
  File "D:\spdl-southpark\spdl.py", line 362, in get_all_seasons
    for season in self.get_season_numbers():
  File "D:\spdl-southpark\spdl.py", line 353, in get_season_numbers
    return sorted(set([int(x.group(1)) for x in re.finditer(r'data-value="season-(\d+)"', resp)])) or list(range(24))
  File "C:\Python39\lib\re.py", line 248, in finditer
    return _compile(pattern, flags).finditer(string)
TypeError: cannot use a string pattern on a bytes-like object

```

This happens on WIndows and Mac with Python 3.9.1

**Comment by mrmk85** [comment]
I can confirm, same here on ubuntu 20.04

/edit
Python 3.8.5


Collecting episodes to download...
Traceback (most recent call last):
  File "spdl.py", line 489, in <module>
    for season in s.get_all_seasons():
  File "spdl.py", line 363, in get_all_seasons
    yield self.get_season(season)
  File "spdl.py", line 380, in get_season
    season_data = json.loads(http_get(url))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ruben280302** [comment]
same issue with macOS 11.1 python 3.8.5


% python3 spdl.py S01
Collecting episodes to download...
Traceback (most recent call last):
  File "spdl.py", line 515, in <module>
    for e in s.get_season(season).episodes:
  File "spdl.py", line 380, in get_season
    season_data = json.loads(http_get(url))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by rgkobashi** [comment]
Yep, same issue with macOS 10.15.7 and python 3.9.1:

```
Collecting episodes to download...
Traceback (most recent call last):
  File "/Users/kobashi/Downloads/spdl-southpark-downloader-master/spdl.py", line 489, in <module>
    for season in s.get_all_seasons():
  File "/Users/kobashi/Downloads/spdl-southpark-downloader-master/spdl.py", line 363, in get_all_seasons
    yield self.get_season(season)
  File "/Users/kobashi/Downloads/spdl-southpark-downloader-master/spdl.py", line 380, in get_season
    season_data = json.loads(http_get(url))
  File "/Users/kobashi/.pyenv/versions/3.9.1/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/kobashi/.pyenv/versions/3.9.1/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/kobashi/.pyenv/versions/3.9.1/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by ThisLimn0** [comment]
Same for me but i think the Dev has abadoned the project...

**Comment by mityax** [comment]
Oh hey there, didn't see this issue before. Seems like an API change on southpark's side... I'm currently very busy and cannot promise I'll fix this soon but I'll have a look as soon as possible.
If anyone wants to create a PR, you'd be welcome :)

**Comment by tfga** [comment]
The url that is being used returns a `301` (for my location, at least):

```
$ curl -i 'https://southpark.cc.com/feeds/carousel/video/06bb4aa7-9917-4b6a-ae93-5ed7be79556a/30/1/json/!airdate/season-9?lang=en'
HTTP/2 301
server: AkamaiGHost
content-length: 0
location: https://www.southparkstudios.com.br/feeds/carousel/video/06bb4aa7-9917-4b6a-ae93-5ed7be79556a/30/1/json/!airdate/season-9?lang=en
date: Thu, 15 Apr 2021 07:01:45 GMT
```

and if you follow the redirect, you get a `404`. :neutral_face:

**Comment by JohnTrunix** [comment]
Is anyone working on a PR or has found a solution? @mityax

**Comment by ThisLimn0** [comment]
Well, yt-dlp‘s south park downloader is working properly again.
